version: "3"

services:
  ### DB ################################################
  db:
    image: postgres:9.6-alpine
    container_name: sample-db
    networks:
      - enterprise_net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${USER_POSTGRES}
      - POSTGRES_PASSWORD=${PASS_POSTGRES}
      - POSTGRES_DB=${DB_DEFAULT}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  ### Redis ################################################
  redis:
    image: redis:4-alpine
    container_name: sample-redis
    networks:
      - enterprise_net
    ports:
      - 6379:6379

networks:
  enterprise_net:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
